[project]
name = "congenial-octo-telegram"
version = "0.1.0"
description = "A small project for learning pourposing"
requires-python = ">=3.8"

dependencies = [
    "pandas",
    "openpyxl",
    "xlsxwriter",
]
